### ISSUE TITLE
Unraid Docker issues

### ISSUE THREAD

**Issue by JuanIsOnline** [ad3m3r5/scratch-map#24]
Good day. I know this might not be something you can help with as the Unraid Template was created but someone else (I think anyways) but I would like to ask just in case maybe you can :). 

I installed the app in Unraid from the Community Application. The template looks like this:
<img width="1142" alt="Screenshot 2024-11-26 at 7 30 42 AM" src="https://github.com/user-attachments/assets/8bc11b69-6ab6-4429-a161-5a10be703f57">
<img width="988" alt="Screenshot 2024-11-26 at 7 31 30 AM" src="https://github.com/user-attachments/assets/2dcd58f2-a567-4a3a-8571-04e980f13e93">

I have tried to change things on it and still, I always get this error:
```
node:fs:596
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open '/data/.db.json.tmp'
    at Object.openSync (node:fs:596:3)
    at Object.writeFileSync (node:fs:2322:35)
    at TextFileSync.write (file:///app/node_modules/lowdb/lib/adapters/TextFileSync.js:36:12)
    at JSONFileSync.write (file:///app/node_modules/lowdb/lib/adapters/JSONFileSync.js:29:66)
    at LowSync.write (file:///app/node_modules/lowdb/lib/LowSync.js:28:26)
    at createConnection (file:///app/utils/database.js:42:6)
    at file:///app/server.js:44:7
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/data/.db.json.tmp'
}

Node.js v18.20.4
```

Thanks.

**Comment by JuanIsOnline** [comment]
So I think this has NOTHING to do with you app itself. 

I was able to get this working by changing the permissions in the `appdata/scratch_map` folder to RW for every option. I don't know if that is something that can be done via the template itself, but since I do not know, I did it manually. That seemed to have worked perfectly.

**Comment by kfoxton** [comment]
Thanks, this helped me as well.
